### ISSUE TITLE
Can we add a step where a new video is created

### ISSUE THREAD

**Issue by springcoil** [mfranzon/dubbing-ai#2]
Hey - great work. The mp3 is great but I'm wondering if we could add another step where the dubbed video is created too. How hard would that be?

**Comment by mfranzon** [comment]
Hey @springcoil ! Thank you to suggest this cool idea. I think that shouldn't be too hard.
I propose two steps:

1.
An idea can be use `moviepy` library  and add change the audio track when I got the response from API.
This is the fastest way I have in mind.

2.
More complex one, but much more precise could be create a lips recognizer using `OpenCV`.
In this way, It could be possible increase the accuracy between new audio track and video.

I can quickly implement the first one and let's see the result😁

**Comment by springcoil** [comment]
First idea is fine 🙂

**Comment by mfranzon** [comment]
Great! I'll send you a message when I have done! 😀

**Comment by mfranzon** [comment]
Hi @springcoil, 
I have added the dubbed video creation without post editing. 
Now, at the end of the execution, in the working directory, you will find a file called Dubbed_{filename}.mp4!
Please, have a look on that and let me know if comes close to what you meant :)

**Comment by springcoil** [comment]
I'll have a look now.

**Comment by springcoil** [comment]
`(dubbing-ai-7drOWZ1D-py3.9) user@192 dubbing-ai % python main.py -h
Traceback (most recent call last):
  File "/Users/user/Code/dubbing-ai/main.py", line 37, in <module>
    args = parser.parse_args()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1824, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1857, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2066, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2006, in consume_optional
    take_action(action, args, option_string)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1934, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1098, in __call__
    parser.print_help()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2554, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2538, in format_help
    return formatter.format_help()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 283, in format_help
    help = self._root_section.format_help()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 532, in _format_action
    if action.help and action.help.strip():
AttributeError: 'tuple' object has no attribute 'strip'`

I get the error here. Any idea?

**Comment by springcoil** [comment]
Then when I run it - I get a video produced but with no sound :(

**Comment by mfranzon** [comment]
Hi @springcoil, 
the broken helper is due to a typo, I added a coma between strings so It was read as tuple not string.
Regarding the absence of sound, It can be related to the fact that in the requirements there wasn't `moviepy`. Now I have updated the requirements. 
If you can re-try to install the requirements, now all should works fine.
